{"name": "test_search_api_invalid_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 200\n +  where 401 = <Response [401]>.status_code", "trace": "@given('The user hits the search api with invalid auth')\n    def test_search_api_invalid_auth():\n        url = data['basic']['url']\n    \n        headers = data['search_invalid_auth']['headers']\n    \n        querystring = data['search_invalid_auth']['querystring']\n        response = requests.get(url, headers=headers, params=querystring)\n    \n        with allure.step(\"Search api hit with invalid auth\"):\n>           assert response.status_code == data['search_invalid_auth']['expected_output']\nE           assert 401 == 200\nE            +  where 401 = <Response [401]>.status_code\n\nstep_defs\\test_search_api.py:33: AssertionError"}, "steps": [{"name": "Search api hit with invalid auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 200\n +  where 401 = <Response [401]>.status_code\n", "trace": "  File \"C:\\Users\\Lenovo\\PycharmProjects\\Prudent\\step_defs\\test_search_api.py\", line 33, in test_search_api_invalid_auth\n    assert response.status_code == data['search_invalid_auth']['expected_output']\n"}, "start": 1706984299117, "stop": 1706984299118}], "start": 1706984298063, "stop": 1706984299119, "uuid": "390cb00b-6df5-427a-b8f9-11ca47f7b002", "historyId": "4bfe66c52d5993279f4108d45a518cc7", "testCaseId": "4bfe66c52d5993279f4108d45a518cc7", "fullName": "step_defs.test_search_api#test_search_api_invalid_auth", "labels": [{"name": "parentSuite", "value": "step_defs"}, {"name": "suite", "value": "test_search_api"}, {"name": "host", "value": "DESKTOP-7LBLCDO"}, {"name": "thread", "value": "4736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "step_defs.test_search_api"}]}